"        _
" __   _(_)_ __ ___  _ __ ___
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__
"   \_/ |_|_| |_| |_|_|  \___|

set nocompatible
filetype off

set rtp+=/usr/local/opt/fzf
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
if has('nvim')
    Plugin 'Shougo/deoplete.nvim', { 'do': ':UpdateRemotePlugins' }
else
    Plugin 'Shougo/deoplete.nvim'
    Plugin 'roxma/nvim-yarp'
    Plugin 'roxma/vim-hug-neovim-rpc'
endif
let g:deoplete#enable_at_startup = 1
Plugin 'dense-analysis/ale'
Plugin 'jiangmiao/auto-pairs'
Plugin 'deoplete-plugins/deoplete-jedi'
Plugin 'junegunn/goyo.vim'
Plugin 'davidhalter/jedi-vim'
Plugin 'SirVer/ultisnips'
Plugin 'mhinz/vim-signify'
Plugin 'honza/vim-snippets'
Plugin 'tpope/vim-surround'
Plugin 'vimwiki/vimwiki'
" Colorschemes
Plugin 'romainl/Apprentice'
Plugin 'NLKNguyen/papercolor-theme'
Plugin 'gosukiwi/vim-atom-dark'
call vundle#end()

filetype plugin indent on
"set background=dark
colorscheme PaperColor

"Use 'gf' to jump to file under cursor
source $HOME/.vim/mappings.vimrc
source $HOME/.vim/general.vimrc
source $HOME/.vim/autocommands.vimrc
source $HOME/.vim/plugins.vimrc
